spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/users/**
        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
        - id: message-service
          uri: http://localhost:8082
          predicates:
            - Path=/messages/**
        - id: category-service
          uri: http://localhost:8081
          predicates:
            - Path=/categories/**
server:
  port: 8080
